### ISSUE TITLE
Add option to choose between padding and margin as gutter

### ISSUE THREAD

**Issue by vuhrmeister** [olivierbossel/gridle#33]
Currently gutter is added as padding.

Given the case that you want to build a page with boxes having a background color this approach is not ideal. They would stick to each other, only the content would have the padding. 
With the current approach you would need to wrap each box by a wrapper element having the grid classes assigned.

When using margin you won't need a wrapper element and the boxes are visually separated.

**Comment by olivierbossel** [comment]
Hi,

Thanks for the feedback.
It's not quite simple to integrate this cause the nature of css make that the padding uses the "box-sizing" feature and the margin don't. This make a lot more complexe to handle all the gridle features like pull, push, etc.. But I know that's a quite wanted feature so I will try to take a look at this for the next release... I let you know my progress on that when I have time for that..

Cheers and thanks for the interest you have about gridle!

**Comment by ufisch** [comment]
Ok cool, good to hear. Looking forward …

**Comment by olivierbossel** [comment]
Hi man,

I've checked for your request but by working on the next release, this has been to risky to integrate that and I prefer to work on the flex support and others features requested.
The reason for that is because I like to see grid elements as a shelf and then put your elements in that shelf. Is the best world, you do not have to add other css properties on the grid elements. Grid elements are grid only, then you put another div in it with your own styling..
Is that ok for you?
I let you check the next major release that will offer a lot a new features and let me know what you think.
Cheers and thanks for your interest in gridle!
