### ISSUE TITLE
Not compatible with gulp-sass (node-sass): error reading values after on line 32

### ISSUE THREAD

**Issue by rkmax** [olivierbossel/gridle#39]
I'm using gulp-sass in the following task

```js
gulp.task('styles', function() {

    var dir = config.dist + '/css';

    return gulp.src(config.scss) // src/styles/main.scss
        .pipe(sass({
            sourceComments: dist ? 'none' : 'map',
            sourceMap: 'sass',
            outputStyle: dist ? 'compressed' : 'nested',
            includePaths: ['node_modules/gridle/sass']
        }))
        //.pipe(autoprefixer("last 2 versions", "> 1%", "ie 8"))
        .on('error', handleErrors)
        .pipe(gulp.dest(dir))
        //.pipe(gulpif(browserSync.active, browserSync.reload({ stream: true })))
    ;
});
```

if the option `errLogToConsole: true` i the a ` error reading values after  on line 32 in node_modules/gridle/sass/gridle/_common-mixins.scss`

but i dont understand why running the command `sass src/styles/main.scss -Inode_modules/gridle/sass'` works fine

**Comment by olivierbossel** [comment]
Hi,

First, thanks for the interest you have about gridle.
For gulp-sass, it's not the first time that this issue is pointed.. The issue is not in gridle as far as I know.. Gulp-sass use node-sass I think and node-sass use libsass. Accordingly to the node-sass documentation, libsass is not fully featured, this is why gridle is not working in this conditions... Maybe I'm wrong but if you have another explication, let me know cause I'm interested to know :)

> The libsass library is not currently at feature parity with the 3.2 Ruby Gem that most Sass users will use, and has little-to-no support for 3.3 syntax. While we try our best to maintain feature parity with libsass, we can not enable features that have not been implemented in libsass yet.

Cheers!

**Comment by rkmax** [comment]
you're right @olivierbossel, i switch to gulp-ruby-sass and all works fine. thanks

**Comment by olivierbossel** [comment]
perfect :)
