### ISSUE TITLE
Sass DEBUG statement in _generate-mixins.scss

### ISSUE THREAD

**Issue by mgibeau** [olivierbossel/gridle#88]
Hi @olivierbossel, thanks for your work, I just migrated to v2 and noticed the sass compilation outputs a [debug](https://github.com/olivierbossel/gridle/blob/master/sass/gridle/_generate-mixins.scss#L455) statement using `gridle_generate_classes()`.

Is this intended to be left there? I'm using a watcher process and it just fills the console on every save, not sure I see the value.

**Comment by Landish** [comment]
Same here, It's kinda annoying a lil bit : ( 

<img width="357" alt="screen shot 2015-11-22 at 4 06 27 pm" src="https://cloud.githubusercontent.com/assets/534610/11323695/1641b54c-9133-11e5-9f19-746480ad8a11.png">

Plus, it outputs single message twice, not sure why.

**Comment by olivierbossel** [comment]
Hi guys,

That's right you will have this output message for now. I will remove it in next release it's now really needed.
You have the message twice if you let activate the states-classes activate. Otherwise it's because you generate twice the classes..
Let me know!

Cheers and thanks for your interest!

**Comment by olivierbossel** [comment]
Done! 2.0.44
