### ISSUE TITLE
Unable to remove gutters

### ISSUE THREAD

**Issue by optimumorganizing** [olivierbossel/gridle#93]
Hello and thanks for such a great grid. I love it.
I have been using a pre 2.0 version and everything was working as expected.
I am starting a new site using 2.0.43. I love many of the new features row-align is fantastic.
The problem I am having is I am unable to remove gutters applying no-gutter has no effect.
I have spent days trying to figure out what I am doing wrong but to no avail.
I really need to be able to remove and add gutters any idea what the problem could be?
Thanks for you time
Peter

**Comment by optimumorganizing** [comment]
I was able to get no-gutter to work by adding !important to Gridle no gutter in _api.scss
This can't be the right solution.

**Comment by designlobby** [comment]
I have a similar issue with gutters and no_gutters. I can't get this working in a universal mixin (if this is supposed to be possible?)... I have tried different variations with the gutter befoer and after the column count.

My universal mixin that does not work:

    .div {
    	@include gridle ( 24 no_gutter mb 8 gutter md 24 no_gutter );
    }

My standard markup that does work:

    .div {
    	@include gridle ( 24 mb 8 md 24 );
    	@include gridle_no_gutter();
    
    	@include gridle_state ( mb tb ) {
    		@include gridle_gutter();
    	}
    	@include gridle_state ( md lg ) {
    		@include gridle_no_gutter();
    	}
    }

**Comment by kagagnon** [comment]
I used to have the same problem. I ended up making a fork of this project. It can be found here https://github.com/OasisCommunication/gridle.

I haven't heavily tested it, but I use it in production ready sites and work for now. When I encounter a problem, I solve it and push a new version.

I'm pretty sure it can solve the initial problem of `no-gutter` working on all state (until `gutter` is called). It also fix other problems, like rows not having the good gutter when it varies between states...

I haven't tested it yet with universal mixin, it might be interesting to know if it work. Anyway, I don't want to promote my fork since i think Gridle is very efficient, but the last commit of this repository was 2 months ago, so here I am.

**Comment by olivierbossel** [comment]
Hi guys,

First of all, thanks for your interest in gridle.
Sorry to answer your issue with as many delay but I've been quite busy these days.
Kagognon, I let you make some pull requests with your fixes and I will take a look if I merge them into the repo.
Is that ok for you?
Otherwise I will try to fix that asap.

Cheers!

**Comment by kagagnon** [comment]
Hi,

Of course it is! Just did a pull request with all the changes. Feel free to look at it.

Well, I've made 1 pull request. That can be a little bit messy. Tell me if you prefer multiple pull requests and I'll separate them.

So glad to hear from you and great job on that grid system!

**Comment by olivierbossel** [comment]
Hi,

Please be careful that the correct line is :

```scss
.div {
    @include gridle ( 24 no-gutter mb 8 gutter md 24 no-gutter );
}
```

I have updated the documentation that was not correct.

You can download the latest 2.0.45 release by the way.
Let me know!
Cheers!
